### ISSUE TITLE
Unexpected value 'OnlineStatusModule'

### ISSUE THREAD

**Issue by mruknowme** [VadimDez/ngx-online-status#2]
Hey,

I get the following error:
```
Unexpected value 'OnlineStatusModule in /my/path/to/app/folder/node_modules/ngx-online-status/src/app/modules/online-status/online-status.module.d.ts' imported by the module 'AppModule in  /my/path/to/app/folder/src/app/app.module.ts'. Please add a @NgModule annotation.
```

Angular 6.0.8.

Can anyone please explain why this happens and how to fix it?

**Comment by pziewiec** [comment]
the same error

**Comment by redasakhi** [comment]
The same here.. any news !!

**Comment by VadimDez** [comment]
How can I reproduce this?
Have you tried exactly like in the readme? You may refer to the stackblitz demo https://stackblitz.com/edit/ngx-online-status

**Comment by redasakhi** [comment]
I did exactly as in the readme. It works as its supposed to be in Dev mode.
But once i did a build prod it gave back that error message.

**Comment by PaulRichez** [comment]
Same here, don't work on production.

**Comment by hugoliegeard** [comment]
> How can I reproduce this?

I'm having the same issue, same error message.
Working with ng serve... but doesn't on prod with 'build' command.

**Comment by PaulRichez** [comment]
> > How can I reproduce this?
> 
> I'm having the same issue, same error message.
> Working with ng serve... but doesn't on prod with 'build' command.


For my part, I used this:
https://www.npmjs.com/package/@ngx-pwa/offline
It works very well.

**Comment by hugoliegeard** [comment]
> For my part, I used this:
> https://www.npmjs.com/package/@ngx-pwa/offline
> It works very well.

Perfect ! Thank you.
